/* AUTOGENERATED. DON'T MODIFY! 
   Run 'node generate-exports.js' inside this folder to update exports
*/

/* eslint-disable quotes */
/* prettier-ignore  */
/* eslint-disable @typescript-eslint/no-unused-vars */
import React from 'react'

import {ReactComponent as HelpTogether} from '../../../icons/one-tone/HelpTogether.svg'
import {ReactComponent as Internet} from '../../../icons/one-tone/Internet.svg'
import {ReactComponent as Smiley} from '../../../icons/one-tone/Smiley.svg'
import {ReactComponent as Clipboard} from '../../../icons/one-tone/clipboard.svg'
import {ReactComponent as DonateMoney} from '../../../icons/one-tone/donate-money.svg'
import {ReactComponent as Form} from '../../../icons/one-tone/form.svg'
import {ReactComponent as Incomplete} from '../../../icons/one-tone/incomplete.svg'
import {ReactComponent as Like} from '../../../icons/one-tone/like.svg'
import {ReactComponent as MagicStick2} from '../../../icons/one-tone/magic-stick-2.svg'
import {ReactComponent as Point1} from '../../../icons/one-tone/point1.svg'
import {ReactComponent as Point2} from '../../../icons/one-tone/point2.svg'
import {ReactComponent as Point3} from '../../../icons/one-tone/point3.svg'
import {ReactComponent as Point4} from '../../../icons/one-tone/point4.svg'
import {ReactComponent as Point5} from '../../../icons/one-tone/point5.svg'
import {ReactComponent as Point6} from '../../../icons/one-tone/point6.svg'
import {ReactComponent as Point7} from '../../../icons/one-tone/point7.svg'
import {ReactComponent as Step1} from '../../../icons/one-tone/step1.svg'
import {ReactComponent as Step2} from '../../../icons/one-tone/step2.svg'
import {ReactComponent as Step3} from '../../../icons/one-tone/step3.svg'
import {ReactComponent as Step4} from '../../../icons/one-tone/step4.svg'
import {ReactComponent as Step5} from '../../../icons/one-tone/step5.svg'
import {ReactComponent as Step6} from '../../../icons/one-tone/step6.svg'
import {ReactComponent as Step7} from '../../../icons/one-tone/step7.svg'
import {ReactComponent as FireTwoTone} from '../../../icons/two-tone/Fire.svg'
import {ReactComponent as UserHandUpTwoTone} from '../../../icons/two-tone/UserHandUp.svg'
import {ReactComponent as AcademicCapTwoTone} from '../../../icons/two-tone/academicCap.svg'
import {ReactComponent as BackpackTwoTone} from '../../../icons/two-tone/backpack.svg'
import {ReactComponent as CaseTwoTone} from '../../../icons/two-tone/case.svg'
import {ReactComponent as ChatRoundCallTwoTone} from '../../../icons/two-tone/chat-round-call.svg'
import {ReactComponent as DiplomaTwoTone} from '../../../icons/two-tone/diploma.svg'
import {ReactComponent as DocumentAddTwoTone} from '../../../icons/two-tone/document-add.svg'
import {ReactComponent as Flag2TwoTone} from '../../../icons/two-tone/flag-2.svg'
import {ReactComponent as HandStarsTwoTone} from '../../../icons/two-tone/hand-stars.svg'
import {ReactComponent as HashtagChatTwoTone} from '../../../icons/two-tone/hashtag-chat.svg'
import {ReactComponent as LayersMinimalisticTwoTone} from '../../../icons/two-tone/layers-minimalistic.svg'
import {ReactComponent as NotebookBookmarkTwoTone} from '../../../icons/two-tone/notebook-bookmark.svg'
import {ReactComponent as ShieldCrossTwoTone} from '../../../icons/two-tone/shield-cross.svg'
import {ReactComponent as ShieldTwoTone} from '../../../icons/two-tone/shield.svg'
import {ReactComponent as SquareAcademicCapTwoTone} from '../../../icons/two-tone/square-academic-cap.svg'
import {ReactComponent as StarsLineTwoTone} from '../../../icons/two-tone/stars-line.svg'
import {ReactComponent as SuitcaseTagTwoTone} from '../../../icons/two-tone/suitcase-tag.svg'
import {ReactComponent as UserHeartTwoTone} from '../../../icons/two-tone/user-heart.svg'
import {ReactComponent as UserSpeakTwoTone} from '../../../icons/two-tone/user-speak.svg'
import {ReactComponent as UsersGroupTwoRoundedTwoTone} from '../../../icons/two-tone/users-group-two-rounded.svg'
import {ReactComponent as VerifiedCheckTwoTone} from '../../../icons/two-tone/verified-check.svg'
import {ReactComponent as WalletMoneyTwoTone} from '../../../icons/two-tone/wallet-money.svg'
import {ReactComponent as WaterSunTwoTone} from '../../../icons/two-tone/water-sun.svg'

export const iconBase = {
  HelpTogether: <HelpTogether />,
  Internet: <Internet />,
  Smiley: <Smiley />,
  clipboard: <Clipboard />,
  donateMoney: <DonateMoney />,
  form: <Form />,
  incomplete: <Incomplete />,
  like: <Like />,
  magicStick2: <MagicStick2 />,
  point1: <Point1 />,
  point2: <Point2 />,
  point3: <Point3 />,
  point4: <Point4 />,
  point5: <Point5 />,
  point6: <Point6 />,
  point7: <Point7 />,
  step1: <Step1 />,
  step2: <Step2 />,
  step3: <Step3 />,
  step4: <Step4 />,
  step5: <Step5 />,
  step6: <Step6 />,
  step7: <Step7 />,
  FireTwoTone: <FireTwoTone />,
  UserHandUpTwoTone: <UserHandUpTwoTone />,
  academicCapTwoTone: <AcademicCapTwoTone />,
  backpackTwoTone: <BackpackTwoTone />,
  caseTwoTone: <CaseTwoTone />,
  chatRoundCallTwoTone: <ChatRoundCallTwoTone />,
  diplomaTwoTone: <DiplomaTwoTone />,
  documentAddTwoTone: <DocumentAddTwoTone />,
  flag2TwoTone: <Flag2TwoTone />,
  handStarsTwoTone: <HandStarsTwoTone />,
  hashtagChatTwoTone: <HashtagChatTwoTone />,
  layersMinimalisticTwoTone: <LayersMinimalisticTwoTone />,
  notebookBookmarkTwoTone: <NotebookBookmarkTwoTone />,
  shieldCrossTwoTone: <ShieldCrossTwoTone />,
  shieldTwoTone: <ShieldTwoTone />,
  squareAcademicCapTwoTone: <SquareAcademicCapTwoTone />,
  starsLineTwoTone: <StarsLineTwoTone />,
  suitcaseTagTwoTone: <SuitcaseTagTwoTone />,
  userHeartTwoTone: <UserHeartTwoTone />,
  userSpeakTwoTone: <UserSpeakTwoTone />,
  usersGroupTwoRoundedTwoTone: <UsersGroupTwoRoundedTwoTone />,
  verifiedCheckTwoTone: <VerifiedCheckTwoTone />,
  walletMoneyTwoTone: <WalletMoneyTwoTone />,
  waterSunTwoTone: <WaterSunTwoTone />,
}
